# Generated by Django 5.0.14 on 2025-06-01 00:50

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_customers', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Customer',
                'verbose_name_plural': 'Tenant Customers',
                'ordering': ['tenant', 'company_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Form Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_forms', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Form',
                'verbose_name_plural': 'Tenant Forms',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_crm.form')),
            ],
            options={
                'verbose_name': 'Tenant Form Question',
                'verbose_name_plural': 'Tenant Form Questions',
                'ordering': ['form', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Response Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Response Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='app_crm.customer', verbose_name='Responding Customer')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app_crm.form')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app_crm.formquestion')),
            ],
            options={
                'verbose_name': 'Tenant Form Response',
                'verbose_name_plural': 'Tenant Form Responses',
                'ordering': ['created_at'],
            },
        ),
    ]
