# Generated by Django 5.0.14 on 2025-06-01 00:50

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded')], db_index=True, default='COMPLETED', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='External Transaction ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Tenant Payment',
                'verbose_name_plural': 'Tenant Payments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Payment Method Name')),
                ('type_code', models.CharField(blank=True, help_text='An internal code for the payment method type.', max_length=50, null=True, verbose_name='Type Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_global', models.BooleanField(default=False, help_text='If true, this method is available to all tenants or for platform use.', verbose_name='Is Global Method')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Transaction Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('refund_out', 'Refund Issued'), ('refund_in', 'Refund Received'), ('internal', 'Internal Transfer'), ('other', 'Other')], max_length=50, null=True, verbose_name='Category')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('is_global', models.BooleanField(default=False, help_text='If true, this type is available to all tenants or for platform use.', verbose_name='Is Global Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Transaction Type',
                'verbose_name_plural': 'Transaction Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Invoice Number')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('total_amount_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Amount (Manual)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Amount Paid')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes/Terms')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='app_crm.customer')),
            ],
            options={
                'verbose_name': 'Tenant Invoice',
                'verbose_name_plural': 'Tenant Invoices',
                'ordering': ['tenant', '-date', '-id'],
            },
        ),
    ]
