# Generated by Django 5.0.14 on 2025-06-01 00:50

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Campaign Code')),
                ('campaign_name', models.CharField(max_length=255, verbose_name='Campaign Name')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('target_audience', models.JSONField(blank=True, default=dict, verbose_name='Target Audience')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Owari Campaign',
                'verbose_name_plural': 'Owari Campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InternalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='ds_owari/tasks/%Y/%m/', verbose_name='File')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Approval Client'), ('PENDING_INTERNAL_APPROVAL', 'Pending Internal Approval'), ('REQUIRES_INFO', 'Requires Info Additional'), ('REVISION_REQUESTED', 'Revision Requested'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=30, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('feedback_notes', models.TextField(blank=True, verbose_name='Feedback Notes')),
            ],
            options={
                'verbose_name': 'Owari Internal Task',
                'verbose_name_plural': 'Owari Internal Tasks',
                'ordering': ['order', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Position Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Owari Job Position',
                'verbose_name_plural': 'Owari Job Positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfferingCategory',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Category Code')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Owari Service Offering Category',
                'verbose_name_plural': 'Owari Service Offering Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfferingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('differentiator', 'Differentiator'), ('benefit', 'Benefit'), ('characteristic', 'Characteristic'), ('process', 'Process'), ('expected_result', 'Expected Result')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Owari Offering Feature',
                'verbose_name_plural': 'Owari Offering Features',
                'ordering': ['service_offering', 'feature_type'],
            },
        ),
        migrations.CreateModel(
            name='OfferingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('effective_date', models.DateField(default=datetime.date.today, verbose_name='Effective Date')),
            ],
            options={
                'verbose_name': 'Owari Offering Price',
                'verbose_name_plural': 'Owari Offering Price History',
                'ordering': ['service_offering', 'currency', '-effective_date'],
                'get_latest_by': 'effective_date',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Provider Name')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=3, verbose_name='Rating')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
            ],
            options={
                'verbose_name': 'Owari Provider',
                'verbose_name_plural': 'Owari Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Offering Code')),
                ('name', models.CharField(max_length=255, verbose_name='Offering Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_package', models.BooleanField(default=False, verbose_name='Is Package')),
                ('is_subscription', models.BooleanField(default=False, verbose_name='Is Subscription')),
                ('audience', models.TextField(blank=True, null=True, verbose_name='Target Audience')),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='Detailed Description')),
                ('problem_solved', models.TextField(blank=True, null=True, verbose_name='Problem Solved')),
            ],
            options={
                'verbose_name': 'Owari Service Offering',
                'verbose_name_plural': 'Owari Service Offerings',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount (%)')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_offerings', to='app_ds_owari.campaign')),
            ],
            options={
                'verbose_name': 'Owari Campaign Service Offering',
                'verbose_name_plural': 'Owari Campaign Service Offerings',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20, null=True, verbose_name='Preferred Contact Method')),
                ('brand_guidelines', models.FileField(blank=True, null=True, upload_to='owari_clients/brand_guidelines/', verbose_name='Brand Guidelines')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owari_client_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Owari Client',
                'verbose_name_plural': 'Owari Clients',
                'ordering': ['company_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='Hire Date')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salary')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owari_employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Owari Employee',
                'verbose_name_plural': 'Owari Employees',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='InternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(auto_now_add=True, verbose_name='Date Received')),
                ('date_required', models.DateTimeField(verbose_name='Date Required')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PLANNING', 'Planning'), ('IN_PROGRESS', 'In Progress'), ('QUALITY_CHECK', 'Quality Check'), ('PENDING_DELIVERY', 'Pending Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('payment_due_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Due Date')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Internal Note')),
                ('priority', models.PositiveIntegerField(default=3, verbose_name='Priority')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Completion Date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total Amount')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_internal_orders', to='app_ds_owari.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_orders', to='app_ds_owari.client')),
            ],
            options={
                'verbose_name': 'Owari Internal Order',
                'verbose_name_plural': 'Owari Internal Orders',
                'ordering': ['priority', '-date_received'],
            },
        ),
        migrations.CreateModel(
            name='InternalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Invoice Number')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Amount Paid')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes/Terms')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_invoices', to='app_ds_owari.internalorder')),
            ],
            options={
                'verbose_name': 'Owari Internal Invoice',
                'verbose_name_plural': 'Owari Internal Invoices',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InternalOrderServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='app_ds_owari.internalorder')),
            ],
            options={
                'verbose_name': 'Owari Internal Order Service Line',
                'verbose_name_plural': 'Owari Internal Order Service Lines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InternalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='COMPLETED', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='External Transaction ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_payments', to='app_ds_owari.internalinvoice')),
            ],
            options={
                'verbose_name': 'Owari Internal Payment',
                'verbose_name_plural': 'Owari Internal Payments',
                'ordering': ['-date'],
            },
        ),
    ]
