# Generated by Django 5.0.14 on 2025-06-01 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_ds_owari', '0001_initial'),
        ('app_finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpayment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_finances.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='internalpayment',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_finances.transactiontype', verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='internaltask',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_internal_tasks', to='app_ds_owari.employee'),
        ),
        migrations.AddField(
            model_name='internaltask',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_tasks', to='app_ds_owari.internalorder'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app_ds_owari.jobposition', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='internaltask',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_internal_tasks_provider', to='app_ds_owari.provider'),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_offerings', to='app_ds_owari.campaign', verbose_name='Associated Campaign'),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_offerings', to='app_ds_owari.offeringcategory'),
        ),
        migrations.AddField(
            model_name='provider',
            name='services_provided',
            field=models.ManyToManyField(blank=True, related_name='providers', to='app_ds_owari.serviceoffering', verbose_name='Service Offerings Provided'),
        ),
        migrations.AddField(
            model_name='offeringprice',
            name='service_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='app_ds_owari.serviceoffering'),
        ),
        migrations.AddField(
            model_name='offeringfeature',
            name='service_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app_ds_owari.serviceoffering'),
        ),
        migrations.AddField(
            model_name='internalorderserviceline',
            name='service_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_order_lines', to='app_ds_owari.serviceoffering'),
        ),
        migrations.AddField(
            model_name='campaignserviceoffering',
            name='service_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='app_ds_owari.serviceoffering'),
        ),
        migrations.AlterUniqueTogether(
            name='offeringprice',
            unique_together={('service_offering', 'currency', 'effective_date')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignserviceoffering',
            unique_together={('campaign', 'service_offering')},
        ),
    ]
